### ISSUE TITLE
[Clean-up] Main Ticket

### ISSUE THREAD

**Issue by KDwevedi** [Code4GovTech/discord-bot#33]
# Description
Definitive ticket for tracking endpoint for Bot Development
## Bot Functions
- [x] Review data collection necessity for metrics on `discord_engagements` table
## Refactoring
- [ ] #32
- [ ] Review and implement the [Singleton Design Pattern](https://python-patterns.guide/gang-of-four/singleton/) for Supabase class
## Discord Features
- [x] #43 
## Documentation
- [ ] Functional Specification for modules
- [ ] [Help Command](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html?highlight=help%20command#ext-commands-help-command)
- [ ] Technology used
## Security
- [ ] #50 
## Maintainability
- [ ] #7 
- [ ] [mypy](https://mypy.readthedocs.io/en/stable/) for type-checking
- [ ] Dev environment? Discord provides [sharding](https://discord.com/developers/docs/topics/gateway#sharding)
- [ ] Tests

**Comment by karntrehan** [comment]
Blocked due to bandwidth.

**Comment by karntrehan** [comment]
Subsumed under https://github.com/Code4GovTech/server/issues/79
