### ISSUE TITLE
Slash Commands

### ISSUE THREAD

**Issue by KDwevedi** [Code4GovTech/discord-bot#43]
Relevant Resources:
- [Helpful Gist](https://gist.github.com/AbstractUmbra/a9c188797ae194e592efe05fa129c57f#syncing-the-command-tree-in-discordpy)
- [Official Repo Examples](https://github.com/Code4GovTech/discord-bot/issues/43)
- Discord.py 2.0 [Tutorial](https://www.youtube.com/watch?v=S4g-XtpDiZ8&list=PLx9e6Ldz3n4lIz2thDqptpgjS9_O--EZZ&index=2)
- [Syncing](https://stackoverflow.com/questions/75453339/discord-py-slash-command-in-cogs)

**Comment by Srish-ty** [comment]
@KDwevedi , I'm willing to work on this issue, 
Can you please provide more details on this issue.
Are we supposed to add more commands or just change the prefix to slash

**Comment by KDwevedi** [comment]
Hey @Srish-ty, 
This issue is slightly outdated and of lower priority.
If you're interested in working on the discord bot,
- Refactoring
- Adding Observability
- Adding meta commands like help 

are more pertinent goals.
If you're willing to take up some of these contributions, we can discuss further.

**Comment by Srish-ty** [comment]
> Hey @Srish-ty, This issue is slightly outdated and of lower priority. If you're interested in working on the discord bot,
> 
> * Refactoring
> * Adding Observability
> * Adding meta commands like help
> 
> are more pertinent goals. If you're willing to take up some of these contributions, we can discuss further.

Okay, sure.
I want to work on adding meta commands. Can you provide details and the issue link

**Comment by KDwevedi** [comment]
Closing this ticket as [slash commands](https://discord.com/developers/docs/tutorials/upgrading-to-application-commands#:~:text=Slash%20Commands,-Slash%20commands%20are&text=They%20are%20accessed%20by%20typing,server%2C%20or%20nothing%20at%20all.) aren't a requirement
