### ISSUE TITLE
Create a periodic task for collecting messages from discord server.

### ISSUE THREAD

**Issue by KDwevedi** [Code4GovTech/discord-bot#6]
## Description
The command [add_messages](https://github.com/Code4GovTech/discord-bot/blob/f46a08c1d7b5b210efb4f58cddd817238836db7f/cogs/discord_data_scraper.py#L63) collects messages from the C4GT Discord server and saves data in a database.
There is a need to have this task be automated so that it repeats at regular intervals (or at specific times) in the background while the bot is active.

An illustration of a possible implementation for reference:

```
@tasks.loop(seconds=60)  # Runs every 60 seconds
async def my_task():
    guild_id = 1234567890  # Replace with the actual guild ID
    guild = bot.get_guild(guild_id)
    channel_id = 1234567890  # Replace with the actual channel ID
    channel = guild.get_channel(channel_id)

    start_command = bot.get_command('start_task')
    stop_command = bot.get_command('stop_task')

    ctx = await bot.get_context(channel)
    await start_command.invoke(ctx)

    await asyncio.sleep(10)  # Wait for 10 seconds

    await stop_command.invoke(ctx)

@bot.command()
async def start_task(ctx):
    my_task.start()
    await ctx.send('Task started!')

@bot.command()
async def stop_task(ctx):
    my_task.stop()
    await ctx.send('Task stopped!')

bot.run('YOUR_BOT_TOKEN')
```

## Goals:
- [ ] Create a [Bot Task](https://discordpy.readthedocs.io/en/stable/ext/tasks/index.html) to implement above mentioned functionality.
- [ ] Implement [error handling](https://discordpy.readthedocs.io/en/stable/ext/tasks/index.html#discord.ext.tasks.Loop.error) so that the Bot notifies an assignable private channel meant for Bot error notifications.

### Product Name:
C4GT

### Project
Official Code4GovTech Discord Bot

### Organization Name:
Samagra

### Tech Skills Needed:
Python, Quart

### Mentor(s)
@KDwevedi 

### Complexity
Low

### Category
Feature

### Sub Category
Refactoring, Beginner Friendly

**Comment by dixitdeeksha** [comment]
Hey @KDwevedi ,

Can I work on this issue? I'm available and interested in working on this issue

Please let me know if I can proceed with this. Thank you!

**Comment by starks-and-wolves** [comment]
Hi @KDwevedi, I am interested in working on this issue. Can you please assist me with the detailed requirements?

**Comment by rushi-02** [comment]
Hi there! My name is Rushikesh Chavan .I believe I can contribute and would like to work on this issue. Can someone guide me on how to get started?

**Comment by KDwevedi** [comment]
Hey @rushi-02 @dixitdeeksha @starks-and-wolves 
The requirements here are straightforward. We need this discord bot to have a [task](https://discordpy.readthedocs.io/en/stable/ext/tasks/index.html) that goes through the message history of the discord guild/server it is live on and add it to a database.

Take a look at [add_messages](https://github.com/Code4GovTech/discord-bot/blob/f46a08c1d7b5b210efb4f58cddd817238836db7f/cogs/discord_data_scraper.py#L63) which is a [command](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands) that does the same thing. The difference between a command and a task is that tasks are set up to run automatically at specific times or after specific durations.

For each new run of the task, your function should be saving previous times when this task has run as a date-time stamp (probably channel-wise), so that you don't need to iterate through the *entire* history every time.

**Comment by KDwevedi** [comment]
Assume that you have an env variable 'SERVER_ID' that gives you the id of the discord guild/server and add a config.json so that the loop time interval can be configured for this task.

**Comment by KDwevedi** [comment]
If you're going to be contributing, please take a fork from the `development` branch of the repository to raise a PR.

**Comment by starks-and-wolves** [comment]
Hey @KDwevedi, thanks for the detailed description. I ran the Discord data scraper on a test server and got an idea of how Discord scraping works and how data is getting populated in the DB. I will begin implementing the requirements now. Thanks again
