### ISSUE TITLE
[C4GT Discord] FAQ chatbot (pre-defined flow)

### ISSUE THREAD

**Issue by omkar309** [Code4GovTech/discord-bot#65]
Requirement:

Acceptance criteria:

Reason:

**Comment by glitcher007** [comment]
Hii @omkar309 
Requirements: We need to make our login system more secure by adding an extra layer of protection called multi-factor authentication (MFA) for all user accounts

Acceptance Criteria:
Implement MFA for all user accounts, allowing users to enable/disable it in their account settings.
Ensure compatibility with various MFA methods such as SMS, email, authenticator apps, and hardware tokens.
Test the MFA functionality thoroughly to guarantee seamless user experience and security.
Update documentation to reflect the changes made to the authentication system

Reason : I believe I can resolve this issue 

please assign this issue to me

**Comment by MohitNSamagra** [comment]
- Picked by @VedantKhairnar directly
- Demo done - changes suggested

**Comment by karntrehan** [comment]
* Development is done. 
* Deployment is pending. 
* Review tomorrow - Will be tested as well, post review will be deployment.
* Karan / Sasi to support on deployment.

**Comment by MohitNSamagra** [comment]
- Deployment to be picked on 19th

**Comment by MohitNSamagra** [comment]
- Deployment fixes to be done - 20th June

**Comment by MohitNSamagra** [comment]
- Deployment fixes to be done - clarity on fixes by Mon

**Comment by MohitNSamagra** [comment]
- Prod deployment failing - @VedantKhairnar to update

**Comment by MohitNSamagra** [comment]
- To be picked on Wed, 3rd July

**Comment by karntrehan** [comment]
To be deployed today. Sasi has closed.

**Comment by MohitNSamagra** [comment]
- To be moved to C4GT discord server for PT UAT

**Comment by karntrehan** [comment]
- Changes suggested = Private messages. 
- Demo to be done with Vedant.

**Comment by MohitNSamagra** [comment]
- Demo done with Parth - working well
