### ISSUE TITLE
[Program Dashboard] New Column in DB

### ISSUE THREAD

**Issue by MohitNSamagra** [Code4GovTech/discord-bot#69]
**Problem:** The program dashboard currently uses db tables which have a cumulative list of users who have joined discord, github, etc. The requirement is to also have a live user dashboard so there is no discrepancy of data.

**Goal:** A new column has to be added to the table which using which a new current users dashboard can be made. This can be done using the same script that Kanav had made earlier except now this can be run using a cron every day. 

Additonally, SQL queries need to be changed to remove the 6 month decay clauses - to be scoped by PM and done by PT

**Comment by karntrehan** [comment]
Done: https://supabase.com/dashboard/project/kcavhjwafgtoqkqbbqrd/editor/6130712?filter=is_active%3Aeq%3Afalse

**Comment by MohitNSamagra** [comment]
!updateServerData to be sent to c4gt discord bot to update column

**Comment by MohitNSamagra** [comment]
- Tested - discrepancy between users on discord and in supabase

**Comment by MohitNSamagra** [comment]
@karntrehan to update

**Comment by karntrehan** [comment]
## Numbers are matching now. 

![Image](https://github.com/user-attachments/assets/5b2a9420-084f-466d-81e3-02daa082ffcc)

![Image](https://github.com/user-attachments/assets/e8574748-edcf-4def-9d2f-a2beda89c889)

Discord is showing 2 members less. But bot is giving same numbers

![Image](https://github.com/user-attachments/assets/42e41044-9d05-44b1-87bd-8fbd4116bcdc)

## I have also added some comments to the bot itself. It will tell you what it is processing. 

![Image](https://github.com/user-attachments/assets/9a0641e6-0fa8-4b19-a158-87f388937449)
